# Generated by Django 5.0.6 on 2024-06-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_dish_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('image_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(error_messages={'unique': 'Nome già esistente!!! Non è possibile avere due piatti con lo stesso nome.'}, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(error_messages={'unique': 'Nome già esistente!!! Non è possibile avere due ingreidenti con lo stesso nome.'}, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.PositiveIntegerField(error_messages={'unique': 'Numero già esistente!!! Non è possibile avere due tavoli con lo stesso numero.'}, unique=True),
        ),
    ]
